spring:
  codec:
    max-in-memory-size: 512000000
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,loggers,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

cron:
  # each :30 on the hour
  collection: "0 30 * * * *"

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

