spring:
  application:
    name: cf-hoover-ui
  codec:
    max-in-memory-size: 512000000
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.hooverRegistry.credentials.uri:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,loggers,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,com.github.appreciated.apexcharts

cron:
  # each :30 on the hour
  collection: "0 30 * * * *"

---
spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    discovery:
      enabled: true

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

