spring:
  application:
    name: cf-hoover-ui
  codec:
    max-in-memory-size: 512000000
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
  threads:
    virtual:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.hooverRegistry.credentials.uri:http://localhost:8761}/eureka/

management:
  info:
    build:
      enabled: true
    dependencies:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    sbom:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,loggers,metrics,prometheus,sbom
  endpoint:
    health:
      show-details: always

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.github.appreciated.apexcharts

cron:
  # each :30 on the hour
  collection: "0 30 * * * *"

---
spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    discovery:
      enabled: true
  threads:
    virtual:
      enabled: true

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

